name: Laravel Filament CI with Auto-Format

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  format-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: campus_connect
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, mysql, pdo, pdo_mysql, dom, fileinfo
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run Laravel Pint (Auto-fix)
        run: ./vendor/bin/pint --preset laravel

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: campus_connect
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan migrate --force

      - name: Install Node Dependencies
        run: npm ci

      - name: Run Prettier (Auto-fix)
        run: npx prettier --write "resources/**/*.{js,ts,vue,jsx,tsx,blade.php}"

      - name: Commit formatted code
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: auto-format code via GitHub Actions" && git push

      - name: Run PHPUnit Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: campus_connect
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan test
